version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.google.protobuf:protobuf-java"
        versions: [">=3.25.1"]
    dependency-groups:
      - name: gradle
        patterns:
          - "*"
