// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package org.vdaas.vald.payload;

public interface ControllOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payload.Controll)
    com.google.protobuf.MessageOrBuilder {
}
