// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package org.vdaas.vald.payload;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payload.Info)
    com.google.protobuf.MessageOrBuilder {
}
