// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package org.vdaas.vald.payload;

public final class ValdPayload {
  private ValdPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Search_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Search_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Search_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Search_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Search_IDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Search_IDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Search_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Search_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Search_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Search_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_Keys_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_Keys_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_Val_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_Val_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_Vals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_Vals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_KeyVal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_KeyVal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Meta_KeyVals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Meta_KeyVals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_Distance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_Distance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_ID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_IDs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_IDs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Object_Vectors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Object_Vectors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Control_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Control_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Control_CreateIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Control_CreateIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Discoverer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Discoverer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Discoverer_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Discoverer_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_GetVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_GetVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_GetVector_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_GetVector_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Locations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Locations_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Locations_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Locations_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Remove_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Remove_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Remove_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Remove_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Remove_RequestMulti_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Remove_RequestMulti_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_IP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_IP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_IP_Register_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_IP_Register_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_IP_Register_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_IP_Register_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_IP_Remove_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_IP_Remove_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_IP_Remove_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_IP_Remove_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_MetaVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_MetaVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_MetaVectors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_MetaVectors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Compressed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Compressed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Compressed_MetaVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Compressed_MetaVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Backup_Compressed_MetaVectors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Backup_Compressed_MetaVectors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Index_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Index_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Index_Count_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Index_Count_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Index_UUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Index_UUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Index_UUID_Committed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Index_UUID_Committed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Index_UUID_Uncommitted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Index_UUID_Uncommitted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Pod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Pod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_CPU_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_CPU_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Memory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Memory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Pods_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Pods_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_Nodes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_Nodes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Info_IPs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Info_IPs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayload.proto\022\007payload\032\027validate/valid" +
      "ate.proto\"\237\002\n\006Search\032K\n\007Request\022\030\n\006vecto" +
      "r\030\001 \003(\002B\010\372B\005\222\001\002\010\002\022&\n\006config\030\002 \001(\0132\026.payl" +
      "oad.Search.Config\032?\n\tIDRequest\022\n\n\002id\030\001 \001" +
      "(\t\022&\n\006config\030\002 \001(\0132\026.payload.Search.Conf" +
      "ig\032P\n\006Config\022\024\n\003num\030\001 \001(\rB\007\372B\004*\002(\001\022\016\n\006ra" +
      "dius\030\002 \001(\002\022\017\n\007epsilon\030\003 \001(\002\022\017\n\007timeout\030\004" +
      " \001(\003\0325\n\010Response\022)\n\007results\030\001 \003(\0132\030.payl" +
      "oad.Object.Distance\"\254\001\n\004Meta\032\022\n\003Key\022\013\n\003k" +
      "ey\030\001 \001(\t\032\024\n\004Keys\022\014\n\004keys\030\001 \003(\t\032\022\n\003Val\022\013\n" +
      "\003val\030\001 \001(\t\032\024\n\004Vals\022\014\n\004vals\030\001 \003(\t\032\"\n\006KeyV" +
      "al\022\013\n\003key\030\001 \001(\t\022\013\n\003val\030\002 \001(\t\032,\n\007KeyVals\022" +
      "!\n\003kvs\030\001 \003(\0132\024.payload.Meta.KeyVal\"\316\001\n\006O" +
      "bject\032(\n\010Distance\022\n\n\002id\030\001 \001(\t\022\020\n\010distanc" +
      "e\030\002 \001(\002\032\031\n\002ID\022\023\n\002id\030\001 \001(\tB\007\372B\004r\002\020\001\032\022\n\003ID" +
      "s\022\013\n\003ids\030\001 \003(\t\0327\n\006Vector\022\023\n\002id\030\001 \001(\tB\007\372B" +
      "\004r\002\020\001\022\030\n\006vector\030\002 \003(\002B\010\372B\005\222\001\002\010\002\0322\n\007Vecto" +
      "rs\022\'\n\007vectors\030\001 \003(\0132\026.payload.Object.Vec" +
      "tor\";\n\007Control\0320\n\022CreateIndexRequest\022\032\n\t" +
      "pool_size\030\001 \001(\rB\007\372B\004*\002(\000\"O\n\nDiscoverer\032A" +
      "\n\007Request\022\025\n\004name\030\001 \001(\tB\007\372B\004r\002\020\001\022\021\n\tname" +
      "space\030\002 \001(\t\022\014\n\004node\030\003 \001(\t\"\334\004\n\006Backup\032-\n\t" +
      "GetVector\032 \n\007Request\022\025\n\004uuid\030\001 \001(\tB\007\372B\004r" +
      "\002\020\001\032-\n\tLocations\032 \n\007Request\022\025\n\004uuid\030\001 \001(" +
      "\tB\007\372B\004r\002\020\001\032S\n\006Remove\032 \n\007Request\022\025\n\004uuid\030" +
      "\001 \001(\tB\007\372B\004r\002\020\001\032\'\n\014RequestMulti\022\027\n\005uuids\030" +
      "\001 \003(\tB\010\372B\005\222\001\002\010\001\032u\n\002IP\032C\n\010Register\0327\n\007Req" +
      "uest\022\025\n\004uuid\030\001 \001(\tB\007\372B\004r\002\020\001\022\025\n\003ips\030\002 \003(\t" +
      "B\010\372B\005\222\001\002\010\001\032*\n\006Remove\032 \n\007Request\022\025\n\003ips\030\001" +
      " \003(\tB\010\372B\005\222\001\002\010\001\032O\n\nMetaVector\022\014\n\004uuid\030\001 \001" +
      "(\t\022\014\n\004meta\030\002 \001(\t\022\030\n\006vector\030\003 \003(\002B\010\372B\005\222\001\002" +
      "\010\002\022\013\n\003ips\030\004 \003(\t\032:\n\013MetaVectors\022+\n\007vector" +
      "s\030\001 \003(\0132\032.payload.Backup.MetaVector\032\232\001\n\n" +
      "Compressed\032E\n\nMetaVector\022\014\n\004uuid\030\001 \001(\t\022\014" +
      "\n\004meta\030\002 \001(\t\022\016\n\006vector\030\003 \001(\014\022\013\n\003ips\030\004 \003(" +
      "\t\032E\n\013MetaVectors\0226\n\007vectors\030\001 \003(\0132%.payl" +
      "oad.Backup.Compressed.MetaVector\"\340\005\n\004Inf" +
      "o\032\207\001\n\005Index\032>\n\005Count\022\016\n\006stored\030\001 \001(\r\022\023\n\013" +
      "uncommitted\030\002 \001(\r\022\020\n\010indexing\030\003 \001(\010\032>\n\004U" +
      "UID\032\031\n\tCommitted\022\014\n\004uuid\030\001 \001(\t\032\033\n\013Uncomm" +
      "itted\022\014\n\004uuid\030\001 \001(\t\032\265\001\n\003Pod\022\020\n\010app_name\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tnamespace\030\003 \001(\t\022\023" +
      "\n\002ip\030\004 \001(\tB\007\372B\004r\002x\001\022\036\n\003cpu\030\005 \001(\0132\021.paylo" +
      "ad.Info.CPU\022$\n\006memory\030\006 \001(\0132\024.payload.In" +
      "fo.Memory\022 \n\004node\030\007 \001(\0132\022.payload.Info.N" +
      "ode\032\252\001\n\004Node\022\014\n\004name\030\001 \001(\t\022\025\n\rinternal_a" +
      "ddr\030\002 \001(\t\022\025\n\rexternal_addr\030\003 \001(\t\022\036\n\003cpu\030" +
      "\004 \001(\0132\021.payload.Info.CPU\022$\n\006memory\030\005 \001(\013" +
      "2\024.payload.Info.Memory\022 \n\004Pods\030\006 \001(\0132\022.p" +
      "ayload.Info.Pods\0324\n\003CPU\022\r\n\005limit\030\001 \001(\001\022\017" +
      "\n\007request\030\002 \001(\001\022\r\n\005usage\030\003 \001(\001\0327\n\006Memory" +
      "\022\r\n\005limit\030\001 \001(\001\022\017\n\007request\030\002 \001(\001\022\r\n\005usag" +
      "e\030\003 \001(\001\0321\n\004Pods\022)\n\004pods\030\001 \003(\0132\021.payload." +
      "Info.PodB\010\372B\005\222\001\002\010\001\0324\n\005Nodes\022+\n\005nodes\030\001 \003" +
      "(\0132\022.payload.Info.NodeB\010\372B\005\222\001\002\010\001\032\021\n\003IPs\022" +
      "\n\n\002ip\030\001 \003(\t\"\007\n\005EmptyBP\n\026org.vdaas.vald.p" +
      "ayloadB\013ValdPayloadP\001Z\'github.com/vdaas/" +
      "vald/apis/grpc/payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_payload_Search_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payload_Search_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Search_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Search_Request_descriptor =
      internal_static_payload_Search_descriptor.getNestedTypes().get(0);
    internal_static_payload_Search_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Search_Request_descriptor,
        new java.lang.String[] { "Vector", "Config", });
    internal_static_payload_Search_IDRequest_descriptor =
      internal_static_payload_Search_descriptor.getNestedTypes().get(1);
    internal_static_payload_Search_IDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Search_IDRequest_descriptor,
        new java.lang.String[] { "Id", "Config", });
    internal_static_payload_Search_Config_descriptor =
      internal_static_payload_Search_descriptor.getNestedTypes().get(2);
    internal_static_payload_Search_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Search_Config_descriptor,
        new java.lang.String[] { "Num", "Radius", "Epsilon", "Timeout", });
    internal_static_payload_Search_Response_descriptor =
      internal_static_payload_Search_descriptor.getNestedTypes().get(3);
    internal_static_payload_Search_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Search_Response_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_payload_Meta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payload_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Meta_Key_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(0);
    internal_static_payload_Meta_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_Key_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_payload_Meta_Keys_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(1);
    internal_static_payload_Meta_Keys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_Keys_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_payload_Meta_Val_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(2);
    internal_static_payload_Meta_Val_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_Val_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_payload_Meta_Vals_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(3);
    internal_static_payload_Meta_Vals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_Vals_descriptor,
        new java.lang.String[] { "Vals", });
    internal_static_payload_Meta_KeyVal_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(4);
    internal_static_payload_Meta_KeyVal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_KeyVal_descriptor,
        new java.lang.String[] { "Key", "Val", });
    internal_static_payload_Meta_KeyVals_descriptor =
      internal_static_payload_Meta_descriptor.getNestedTypes().get(5);
    internal_static_payload_Meta_KeyVals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Meta_KeyVals_descriptor,
        new java.lang.String[] { "Kvs", });
    internal_static_payload_Object_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_payload_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Object_Distance_descriptor =
      internal_static_payload_Object_descriptor.getNestedTypes().get(0);
    internal_static_payload_Object_Distance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_Distance_descriptor,
        new java.lang.String[] { "Id", "Distance", });
    internal_static_payload_Object_ID_descriptor =
      internal_static_payload_Object_descriptor.getNestedTypes().get(1);
    internal_static_payload_Object_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_ID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_payload_Object_IDs_descriptor =
      internal_static_payload_Object_descriptor.getNestedTypes().get(2);
    internal_static_payload_Object_IDs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_IDs_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_payload_Object_Vector_descriptor =
      internal_static_payload_Object_descriptor.getNestedTypes().get(3);
    internal_static_payload_Object_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_Vector_descriptor,
        new java.lang.String[] { "Id", "Vector", });
    internal_static_payload_Object_Vectors_descriptor =
      internal_static_payload_Object_descriptor.getNestedTypes().get(4);
    internal_static_payload_Object_Vectors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Object_Vectors_descriptor,
        new java.lang.String[] { "Vectors", });
    internal_static_payload_Control_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_payload_Control_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Control_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Control_CreateIndexRequest_descriptor =
      internal_static_payload_Control_descriptor.getNestedTypes().get(0);
    internal_static_payload_Control_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Control_CreateIndexRequest_descriptor,
        new java.lang.String[] { "PoolSize", });
    internal_static_payload_Discoverer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_payload_Discoverer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Discoverer_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Discoverer_Request_descriptor =
      internal_static_payload_Discoverer_descriptor.getNestedTypes().get(0);
    internal_static_payload_Discoverer_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Discoverer_Request_descriptor,
        new java.lang.String[] { "Name", "Namespace", "Node", });
    internal_static_payload_Backup_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_payload_Backup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_GetVector_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_GetVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_GetVector_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_GetVector_Request_descriptor =
      internal_static_payload_Backup_GetVector_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_GetVector_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_GetVector_Request_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_Backup_Locations_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(1);
    internal_static_payload_Backup_Locations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Locations_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_Locations_Request_descriptor =
      internal_static_payload_Backup_Locations_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_Locations_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Locations_Request_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_Backup_Remove_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(2);
    internal_static_payload_Backup_Remove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Remove_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_Remove_Request_descriptor =
      internal_static_payload_Backup_Remove_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_Remove_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Remove_Request_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_Backup_Remove_RequestMulti_descriptor =
      internal_static_payload_Backup_Remove_descriptor.getNestedTypes().get(1);
    internal_static_payload_Backup_Remove_RequestMulti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Remove_RequestMulti_descriptor,
        new java.lang.String[] { "Uuids", });
    internal_static_payload_Backup_IP_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(3);
    internal_static_payload_Backup_IP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_IP_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_IP_Register_descriptor =
      internal_static_payload_Backup_IP_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_IP_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_IP_Register_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_IP_Register_Request_descriptor =
      internal_static_payload_Backup_IP_Register_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_IP_Register_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_IP_Register_Request_descriptor,
        new java.lang.String[] { "Uuid", "Ips", });
    internal_static_payload_Backup_IP_Remove_descriptor =
      internal_static_payload_Backup_IP_descriptor.getNestedTypes().get(1);
    internal_static_payload_Backup_IP_Remove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_IP_Remove_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_IP_Remove_Request_descriptor =
      internal_static_payload_Backup_IP_Remove_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_IP_Remove_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_IP_Remove_Request_descriptor,
        new java.lang.String[] { "Ips", });
    internal_static_payload_Backup_MetaVector_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(4);
    internal_static_payload_Backup_MetaVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_MetaVector_descriptor,
        new java.lang.String[] { "Uuid", "Meta", "Vector", "Ips", });
    internal_static_payload_Backup_MetaVectors_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(5);
    internal_static_payload_Backup_MetaVectors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_MetaVectors_descriptor,
        new java.lang.String[] { "Vectors", });
    internal_static_payload_Backup_Compressed_descriptor =
      internal_static_payload_Backup_descriptor.getNestedTypes().get(6);
    internal_static_payload_Backup_Compressed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Compressed_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Backup_Compressed_MetaVector_descriptor =
      internal_static_payload_Backup_Compressed_descriptor.getNestedTypes().get(0);
    internal_static_payload_Backup_Compressed_MetaVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Compressed_MetaVector_descriptor,
        new java.lang.String[] { "Uuid", "Meta", "Vector", "Ips", });
    internal_static_payload_Backup_Compressed_MetaVectors_descriptor =
      internal_static_payload_Backup_Compressed_descriptor.getNestedTypes().get(1);
    internal_static_payload_Backup_Compressed_MetaVectors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Backup_Compressed_MetaVectors_descriptor,
        new java.lang.String[] { "Vectors", });
    internal_static_payload_Info_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_payload_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Info_Index_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(0);
    internal_static_payload_Info_Index_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Index_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Info_Index_Count_descriptor =
      internal_static_payload_Info_Index_descriptor.getNestedTypes().get(0);
    internal_static_payload_Info_Index_Count_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Index_Count_descriptor,
        new java.lang.String[] { "Stored", "Uncommitted", "Indexing", });
    internal_static_payload_Info_Index_UUID_descriptor =
      internal_static_payload_Info_Index_descriptor.getNestedTypes().get(1);
    internal_static_payload_Info_Index_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Index_UUID_descriptor,
        new java.lang.String[] { });
    internal_static_payload_Info_Index_UUID_Committed_descriptor =
      internal_static_payload_Info_Index_UUID_descriptor.getNestedTypes().get(0);
    internal_static_payload_Info_Index_UUID_Committed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Index_UUID_Committed_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_Info_Index_UUID_Uncommitted_descriptor =
      internal_static_payload_Info_Index_UUID_descriptor.getNestedTypes().get(1);
    internal_static_payload_Info_Index_UUID_Uncommitted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Index_UUID_Uncommitted_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_Info_Pod_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(1);
    internal_static_payload_Info_Pod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Pod_descriptor,
        new java.lang.String[] { "AppName", "Name", "Namespace", "Ip", "Cpu", "Memory", "Node", });
    internal_static_payload_Info_Node_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(2);
    internal_static_payload_Info_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Node_descriptor,
        new java.lang.String[] { "Name", "InternalAddr", "ExternalAddr", "Cpu", "Memory", "Pods", });
    internal_static_payload_Info_CPU_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(3);
    internal_static_payload_Info_CPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_CPU_descriptor,
        new java.lang.String[] { "Limit", "Request", "Usage", });
    internal_static_payload_Info_Memory_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(4);
    internal_static_payload_Info_Memory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Memory_descriptor,
        new java.lang.String[] { "Limit", "Request", "Usage", });
    internal_static_payload_Info_Pods_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(5);
    internal_static_payload_Info_Pods_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Pods_descriptor,
        new java.lang.String[] { "Pods", });
    internal_static_payload_Info_Nodes_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(6);
    internal_static_payload_Info_Nodes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_Nodes_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_payload_Info_IPs_descriptor =
      internal_static_payload_Info_descriptor.getNestedTypes().get(7);
    internal_static_payload_Info_IPs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Info_IPs_descriptor,
        new java.lang.String[] { "Ip", });
    internal_static_payload_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_payload_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_Empty_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
