name: "Install gRPC Dependencies"
description: "Install gRPC dependencies"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      id: install-dependencies
      run: |
        sudo apt install apt-transport-https curl gnupg -y
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

        sudo apt-get update
        sudo apt-get install -y g++ git bazel
    - name: Install grpc-java
      shell: bash
      id: install-grpc-java
      run: |
        PROTOBUF_VERSION=$(make vald/protobuf/version/print)
        GRPC_JAVA_VERSION=$(make vald/grpc/java/version/print)
        mkdir -p $HOME/protobuf
        curl -L https://github.com/protocolbuffers/protobuf/archive/${PROTOBUF_VERSION}.tar.gz | tar xvz --strip-components=1 -C $HOME/protobuf
        cd $HOME/protobuf
        bazel build :protoc :protobuf
        cp bazel-bin/protoc /usr/local/bin
        mkdir -p $HOME/grpc-java
        curl -L https://github.com/grpc/grpc-java/archive/${GRPC_JAVA_VERSION}.tar.gz | tar xvz --strip-components=1 -C $HOME/grpc-java
        cd $HOME/grpc-java/compiler/src/java_plugin/cpp
        g++ -I. -I$HOME/protobuf/src \
        *.cpp \
        -L$HOME/protobuf/src/.libs \
        -lprotoc -lprotobuf -lpthread --std=c++0x -s \
        -o protoc-gen-grpc-java
        cp protoc-gen-grpc-java $HOME/grpc-java
