// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package org.vdaas.vald.agent;

public final class ValdAgent {
  private ValdAgent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013agent.proto\022\005agent\032\rpayload.proto\032\034goo" +
      "gle/api/annotations.proto2\243\013\n\005Agent\022F\n\006E" +
      "xists\022\022.payload.Object.ID\032\022.payload.Obje" +
      "ct.ID\"\024\202\323\344\223\002\016\022\014/exists/{id}\022O\n\006Search\022\027." +
      "payload.Search.Request\032\030.payload.Search." +
      "Response\"\022\202\323\344\223\002\014\"\007/search:\001*\022X\n\nSearchBy" +
      "ID\022\031.payload.Search.IDRequest\032\030.payload." +
      "Search.Response\"\025\202\323\344\223\002\017\"\n/search/id:\001*\022G" +
      "\n\014StreamSearch\022\027.payload.Search.Request\032" +
      "\030.payload.Search.Response\"\000(\0010\001\022M\n\020Strea" +
      "mSearchByID\022\031.payload.Search.IDRequest\032\030" +
      ".payload.Search.Response\"\000(\0010\001\022D\n\006Insert" +
      "\022\026.payload.Object.Vector\032\016.payload.Empty" +
      "\"\022\202\323\344\223\002\014\"\007/insert:\001*\022<\n\014StreamInsert\022\026.p" +
      "ayload.Object.Vector\032\016.payload.Empty\"\000(\001" +
      "0\001\0228\n\013MultiInsert\022\027.payload.Object.Vecto" +
      "rs\032\016.payload.Empty\"\000\022D\n\006Update\022\026.payload" +
      ".Object.Vector\032\016.payload.Empty\"\022\202\323\344\223\002\014\"\007" +
      "/update:\001*\022<\n\014StreamUpdate\022\026.payload.Obj" +
      "ect.Vector\032\016.payload.Empty\"\000(\0010\001\0228\n\013Mult" +
      "iUpdate\022\027.payload.Object.Vectors\032\016.paylo" +
      "ad.Empty\"\000\022B\n\006Remove\022\022.payload.Object.ID" +
      "\032\016.payload.Empty\"\024\202\323\344\223\002\016*\014/remove/{id}\0228" +
      "\n\014StreamRemove\022\022.payload.Object.ID\032\016.pay" +
      "load.Empty\"\000(\0010\001\0224\n\013MultiRemove\022\023.payloa" +
      "d.Object.IDs\032\016.payload.Empty\"\000\022M\n\tGetObj" +
      "ect\022\022.payload.Object.ID\032\026.payload.Object" +
      ".Vector\"\024\202\323\344\223\002\016\022\014/object/{id}\022C\n\017StreamG" +
      "etObject\022\022.payload.Object.ID\032\026.payload.O" +
      "bject.Vector\"\000(\0010\001\022Y\n\013CreateIndex\022#.payl" +
      "oad.Control.CreateIndexRequest\032\016.payload" +
      ".Empty\"\025\202\323\344\223\002\017\022\r/index/create\022@\n\tSaveInd" +
      "ex\022\016.payload.Empty\032\016.payload.Empty\"\023\202\323\344\223" +
      "\002\r\022\013/index/save\022g\n\022CreateAndSaveIndex\022#." +
      "payload.Control.CreateIndexRequest\032\016.pay" +
      "load.Empty\"\034\202\323\344\223\002\026\022\024/index/createandsave" +
      "\022E\n\tIndexInfo\022\016.payload.Empty\032\023.payload." +
      "Info.Index\"\023\202\323\344\223\002\r\022\013/index/infoBJ\n\024org.v" +
      "daas.vald.agentB\tValdAgentP\001Z%github.com" +
      "/vdaas/vald/apis/grpc/agentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.vdaas.vald.payload.ValdPayload.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.vdaas.vald.payload.ValdPayload.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
