// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/rpc/errdetails/error_details.proto

// Protobuf Java Version: 3.25.3
package org.vdaas.vald.api.v1.rpc;

public final class ErrorDetailsProto {
  private ErrorDetailsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_ErrorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_ErrorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_ErrorInfo_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_ErrorInfo_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_RetryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_RetryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_DebugInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_DebugInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_QuotaFailure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_QuotaFailure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_QuotaFailure_Violation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_QuotaFailure_Violation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_PreconditionFailure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_PreconditionFailure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_PreconditionFailure_Violation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_PreconditionFailure_Violation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_BadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_BadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_BadRequest_FieldViolation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_BadRequest_FieldViolation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_RequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_RequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_ResourceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_ResourceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_Help_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_Help_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_Help_Link_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_Help_Link_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_v1_LocalizedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_v1_LocalizedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%v1/rpc/errdetails/error_details.proto\022" +
      "\006rpc.v1\032\036google/protobuf/duration.proto\"" +
      "\265\001\n\tErrorInfo\022\026\n\006reason\030\001 \001(\tR\006reason\022\026\n" +
      "\006domain\030\002 \001(\tR\006domain\022;\n\010metadata\030\003 \003(\0132" +
      "\037.rpc.v1.ErrorInfo.MetadataEntryR\010metada" +
      "ta\032;\n\rMetadataEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n" +
      "\005value\030\002 \001(\tR\005value:\0028\001\"G\n\tRetryInfo\022:\n\013" +
      "retry_delay\030\001 \001(\0132\031.google.protobuf.Dura" +
      "tionR\nretryDelay\"H\n\tDebugInfo\022#\n\rstack_e" +
      "ntries\030\001 \003(\tR\014stackEntries\022\026\n\006detail\030\002 \001" +
      "(\tR\006detail\"\227\001\n\014QuotaFailure\022>\n\nviolation" +
      "s\030\001 \003(\0132\036.rpc.v1.QuotaFailure.ViolationR" +
      "\nviolations\032G\n\tViolation\022\030\n\007subject\030\001 \001(" +
      "\tR\007subject\022 \n\013description\030\002 \001(\tR\013descrip" +
      "tion\"\271\001\n\023PreconditionFailure\022E\n\nviolatio" +
      "ns\030\001 \003(\0132%.rpc.v1.PreconditionFailure.Vi" +
      "olationR\nviolations\032[\n\tViolation\022\022\n\004type" +
      "\030\001 \001(\tR\004type\022\030\n\007subject\030\002 \001(\tR\007subject\022 " +
      "\n\013description\030\003 \001(\tR\013description\"\244\001\n\nBad" +
      "Request\022L\n\020field_violations\030\001 \003(\0132!.rpc." +
      "v1.BadRequest.FieldViolationR\017fieldViola" +
      "tions\032H\n\016FieldViolation\022\024\n\005field\030\001 \001(\tR\005" +
      "field\022 \n\013description\030\002 \001(\tR\013description\"" +
      "O\n\013RequestInfo\022\035\n\nrequest_id\030\001 \001(\tR\trequ" +
      "estId\022!\n\014serving_data\030\002 \001(\tR\013servingData" +
      "\"\220\001\n\014ResourceInfo\022#\n\rresource_type\030\001 \001(\t" +
      "R\014resourceType\022#\n\rresource_name\030\002 \001(\tR\014r" +
      "esourceName\022\024\n\005owner\030\003 \001(\tR\005owner\022 \n\013des" +
      "cription\030\004 \001(\tR\013description\"k\n\004Help\022\'\n\005l" +
      "inks\030\001 \003(\0132\021.rpc.v1.Help.LinkR\005links\032:\n\004" +
      "Link\022 \n\013description\030\001 \001(\tR\013description\022\020" +
      "\n\003url\030\002 \001(\tR\003url\"D\n\020LocalizedMessage\022\026\n\006" +
      "locale\030\001 \001(\tR\006locale\022\030\n\007message\030\002 \001(\tR\007m" +
      "essageBi\n\031org.vdaas.vald.api.v1.rpcB\021Err" +
      "orDetailsProtoP\001Z1github.com/vdaas/vald/" +
      "apis/grpc/v1/rpc/errdetails\242\002\003RPCb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_rpc_v1_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_v1_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_ErrorInfo_descriptor,
        new java.lang.String[] { "Reason", "Domain", "Metadata", });
    internal_static_rpc_v1_ErrorInfo_MetadataEntry_descriptor =
      internal_static_rpc_v1_ErrorInfo_descriptor.getNestedTypes().get(0);
    internal_static_rpc_v1_ErrorInfo_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_ErrorInfo_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_v1_RetryInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_v1_RetryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_RetryInfo_descriptor,
        new java.lang.String[] { "RetryDelay", });
    internal_static_rpc_v1_DebugInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpc_v1_DebugInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_DebugInfo_descriptor,
        new java.lang.String[] { "StackEntries", "Detail", });
    internal_static_rpc_v1_QuotaFailure_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpc_v1_QuotaFailure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_QuotaFailure_descriptor,
        new java.lang.String[] { "Violations", });
    internal_static_rpc_v1_QuotaFailure_Violation_descriptor =
      internal_static_rpc_v1_QuotaFailure_descriptor.getNestedTypes().get(0);
    internal_static_rpc_v1_QuotaFailure_Violation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_QuotaFailure_Violation_descriptor,
        new java.lang.String[] { "Subject", "Description", });
    internal_static_rpc_v1_PreconditionFailure_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpc_v1_PreconditionFailure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_PreconditionFailure_descriptor,
        new java.lang.String[] { "Violations", });
    internal_static_rpc_v1_PreconditionFailure_Violation_descriptor =
      internal_static_rpc_v1_PreconditionFailure_descriptor.getNestedTypes().get(0);
    internal_static_rpc_v1_PreconditionFailure_Violation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_PreconditionFailure_Violation_descriptor,
        new java.lang.String[] { "Type", "Subject", "Description", });
    internal_static_rpc_v1_BadRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpc_v1_BadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_BadRequest_descriptor,
        new java.lang.String[] { "FieldViolations", });
    internal_static_rpc_v1_BadRequest_FieldViolation_descriptor =
      internal_static_rpc_v1_BadRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_v1_BadRequest_FieldViolation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_BadRequest_FieldViolation_descriptor,
        new java.lang.String[] { "Field", "Description", });
    internal_static_rpc_v1_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpc_v1_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_RequestInfo_descriptor,
        new java.lang.String[] { "RequestId", "ServingData", });
    internal_static_rpc_v1_ResourceInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpc_v1_ResourceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_ResourceInfo_descriptor,
        new java.lang.String[] { "ResourceType", "ResourceName", "Owner", "Description", });
    internal_static_rpc_v1_Help_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpc_v1_Help_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_Help_descriptor,
        new java.lang.String[] { "Links", });
    internal_static_rpc_v1_Help_Link_descriptor =
      internal_static_rpc_v1_Help_descriptor.getNestedTypes().get(0);
    internal_static_rpc_v1_Help_Link_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_Help_Link_descriptor,
        new java.lang.String[] { "Description", "Url", });
    internal_static_rpc_v1_LocalizedMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpc_v1_LocalizedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_v1_LocalizedMessage_descriptor,
        new java.lang.String[] { "Locale", "Message", });
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
