// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/proto/v1/rpc/error_details.proto

package org.vdaas.vald.api.v1.rpc;

public interface HelpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.v1.Help)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * URL(s) pointing to additional information on handling the current error.
   * </pre>
   *
   * <code>repeated .rpc.v1.Help.Link links = 1;</code>
   */
  java.util.List<org.vdaas.vald.api.v1.rpc.Help.Link> 
      getLinksList();
  /**
   * <pre>
   * URL(s) pointing to additional information on handling the current error.
   * </pre>
   *
   * <code>repeated .rpc.v1.Help.Link links = 1;</code>
   */
  org.vdaas.vald.api.v1.rpc.Help.Link getLinks(int index);
  /**
   * <pre>
   * URL(s) pointing to additional information on handling the current error.
   * </pre>
   *
   * <code>repeated .rpc.v1.Help.Link links = 1;</code>
   */
  int getLinksCount();
  /**
   * <pre>
   * URL(s) pointing to additional information on handling the current error.
   * </pre>
   *
   * <code>repeated .rpc.v1.Help.Link links = 1;</code>
   */
  java.util.List<? extends org.vdaas.vald.api.v1.rpc.Help.LinkOrBuilder> 
      getLinksOrBuilderList();
  /**
   * <pre>
   * URL(s) pointing to additional information on handling the current error.
   * </pre>
   *
   * <code>repeated .rpc.v1.Help.Link links = 1;</code>
   */
  org.vdaas.vald.api.v1.rpc.Help.LinkOrBuilder getLinksOrBuilder(
      int index);
}
