// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vald/apis/proto/v1/errors/errors.proto

package org.vdaas.vald.api.v1.errors;

public interface ErrorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:errors.v1.Errors)
    com.google.protobuf.MessageOrBuilder {
}
