// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vald/apis/proto/v1/payload/payload.proto

package org.vdaas.vald.api.v1.payload;

public interface DiscovererOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payload.v1.Discoverer)
    com.google.protobuf.MessageOrBuilder {
}
