// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/proto/v1/payload/payload.proto

package org.vdaas.vald.api.v1.payload;

public interface InsertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payload.v1.Insert)
    com.google.protobuf.MessageOrBuilder {
}
