// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/proto/v1/payload/payload.proto

package org.vdaas.vald.api.v1.payload;

public final class ValdPayload {
  private ValdPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_MultiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_MultiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_IDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_IDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_MultiIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_MultiIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_ObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_ObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_MultiObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_MultiObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_Responses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_Responses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Search_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Search_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Filter_Target_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Filter_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Filter_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Filter_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_MultiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_MultiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_ObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_ObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_MultiObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_MultiObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Insert_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Insert_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_MultiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_MultiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_ObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_ObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_MultiObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_MultiObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Update_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Update_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_MultiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_MultiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_ObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_ObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_MultiObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_MultiObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Upsert_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Upsert_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Remove_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Remove_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Remove_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Remove_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Remove_MultiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Remove_MultiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Remove_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Remove_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_VectorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_VectorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Distance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Distance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_StreamDistance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_StreamDistance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_ID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_IDs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_IDs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Vectors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Vectors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_StreamVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_StreamVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_ReshapeVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_ReshapeVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Blob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Blob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_StreamBlob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_StreamBlob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_StreamLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_StreamLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Object_Locations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Object_Locations_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Control_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Control_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Control_CreateIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Control_CreateIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Discoverer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Discoverer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Discoverer_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Discoverer_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Index_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Index_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Index_Count_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Index_Count_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Index_UUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Index_UUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Index_UUID_Committed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Index_UUID_Committed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Index_UUID_Uncommitted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Index_UUID_Uncommitted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Pod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Pod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_CPU_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_CPU_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Memory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Memory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Pods_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Pods_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_Nodes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_Nodes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Info_IPs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Info_IPs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payload_v1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payload_v1_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#apis/proto/v1/payload/payload.proto\022\np" +
      "ayload.v1\032Agithub.com/envoyproxy/protoc-" +
      "gen-validate/validate/validate.proto\0328gi" +
      "thub.com/googleapis/googleapis/google/rp" +
      "c/status.proto\032]github.com/planetscale/v" +
      "tprotobuf/include/github.com/planetscale" +
      "/vtprotobuf/vtproto/ext.proto\"\271\t\n\006Search" +
      "\032T\n\007Request\022\030\n\006vector\030\001 \003(\002B\010\372B\005\222\001\002\010\002\022)\n" +
      "\006config\030\002 \001(\0132\031.payload.v1.Search.Config" +
      ":\004\250\246\037\001\032B\n\014MultiRequest\022,\n\010requests\030\001 \003(\013" +
      "2\032.payload.v1.Search.Request:\004\250\246\037\001\032H\n\tID" +
      "Request\022\n\n\002id\030\001 \001(\t\022)\n\006config\030\002 \001(\0132\031.pa" +
      "yload.v1.Search.Config:\004\250\246\037\001\032F\n\016MultiIDR" +
      "equest\022.\n\010requests\030\001 \003(\0132\034.payload.v1.Se" +
      "arch.IDRequest:\004\250\246\037\001\032\177\n\rObjectRequest\022\016\n" +
      "\006object\030\001 \001(\014\022)\n\006config\030\002 \001(\0132\031.payload." +
      "v1.Search.Config\022-\n\nvectorizer\030\003 \001(\0132\031.p" +
      "ayload.v1.Filter.Target:\004\250\246\037\001\032N\n\022MultiOb" +
      "jectRequest\0222\n\010requests\030\001 \003(\0132 .payload." +
      "v1.Search.ObjectRequest:\004\250\246\037\001\032\263\002\n\006Config" +
      "\022\022\n\nrequest_id\030\001 \001(\t\022\024\n\003num\030\002 \001(\rB\007\372B\004*\002" +
      "(\001\022\016\n\006radius\030\003 \001(\002\022\017\n\007epsilon\030\004 \001(\002\022\017\n\007t" +
      "imeout\030\005 \001(\003\0222\n\017ingress_filters\030\006 \001(\0132\031." +
      "payload.v1.Filter.Config\0221\n\016egress_filte" +
      "rs\030\007 \001(\0132\031.payload.v1.Filter.Config\022\030\n\007m" +
      "in_num\030\010 \001(\rB\007\372B\004*\002(\000\022F\n\025aggregation_alg" +
      "orithm\030\t \001(\0162\'.payload.v1.Search.Aggrega" +
      "tionAlgorithm:\004\250\246\037\001\032R\n\010Response\022\022\n\nreque" +
      "st_id\030\001 \001(\t\022,\n\007results\030\002 \003(\0132\033.payload.v" +
      "1.Object.Distance:\004\250\246\037\001\032A\n\tResponses\022.\n\t" +
      "responses\030\001 \003(\0132\033.payload.v1.Search.Resp" +
      "onse:\004\250\246\037\001\032r\n\016StreamResponse\022/\n\010response" +
      "\030\001 \001(\0132\033.payload.v1.Search.ResponseH\000\022$\n" +
      "\006status\030\002 \001(\0132\022.google.rpc.StatusH\000B\t\n\007p" +
      "ayload\"k\n\024AggregationAlgorithm\022\013\n\007Unknow" +
      "n\020\000\022\023\n\017ConcurrentQueue\020\001\022\r\n\tSortSlice\020\002\022" +
      "\021\n\rSortPoolSlice\020\003\022\017\n\013PairingHeap\020\004:\004\250\246\037" +
      "\001\"v\n\006Filter\032*\n\006Target\022\014\n\004host\030\001 \001(\t\022\014\n\004p" +
      "ort\030\002 \001(\r:\004\250\246\037\001\032:\n\006Config\022*\n\007targets\030\001 \003" +
      "(\0132\031.payload.v1.Filter.Target:\004\250\246\037\001:\004\250\246\037" +
      "\001\"\236\004\n\006Insert\032o\n\007Request\0223\n\006vector\030\001 \001(\0132" +
      "\031.payload.v1.Object.VectorB\010\372B\005\222\001\002\010\002\022)\n\006" +
      "config\030\002 \001(\0132\031.payload.v1.Insert.Config:" +
      "\004\250\246\037\001\032B\n\014MultiRequest\022,\n\010requests\030\001 \003(\0132" +
      "\032.payload.v1.Insert.Request:\004\250\246\037\001\032\230\001\n\rOb" +
      "jectRequest\022\'\n\006object\030\001 \001(\0132\027.payload.v1" +
      ".Object.Blob\022)\n\006config\030\002 \001(\0132\031.payload.v" +
      "1.Insert.Config\022-\n\nvectorizer\030\003 \001(\0132\031.pa" +
      "yload.v1.Filter.Target:\004\250\246\037\001\032N\n\022MultiObj" +
      "ectRequest\0222\n\010requests\030\001 \003(\0132 .payload.v" +
      "1.Insert.ObjectRequest:\004\250\246\037\001\032n\n\006Config\022\037" +
      "\n\027skip_strict_exist_check\030\001 \001(\010\022*\n\007filte" +
      "rs\030\002 \001(\0132\031.payload.v1.Filter.Config\022\021\n\tt" +
      "imestamp\030\003 \001(\003:\004\250\246\037\001:\004\250\246\037\001\"\300\004\n\006Update\032o\n" +
      "\007Request\0223\n\006vector\030\001 \001(\0132\031.payload.v1.Ob" +
      "ject.VectorB\010\372B\005\222\001\002\010\002\022)\n\006config\030\002 \001(\0132\031." +
      "payload.v1.Update.Config:\004\250\246\037\001\032B\n\014MultiR" +
      "equest\022,\n\010requests\030\001 \003(\0132\032.payload.v1.Up" +
      "date.Request:\004\250\246\037\001\032\230\001\n\rObjectRequest\022\'\n\006" +
      "object\030\001 \001(\0132\027.payload.v1.Object.Blob\022)\n" +
      "\006config\030\002 \001(\0132\031.payload.v1.Update.Config" +
      "\022-\n\nvectorizer\030\003 \001(\0132\031.payload.v1.Filter" +
      ".Target:\004\250\246\037\001\032N\n\022MultiObjectRequest\0222\n\010r" +
      "equests\030\001 \003(\0132 .payload.v1.Update.Object" +
      "Request:\004\250\246\037\001\032\217\001\n\006Config\022\037\n\027skip_strict_" +
      "exist_check\030\001 \001(\010\022*\n\007filters\030\002 \001(\0132\031.pay" +
      "load.v1.Filter.Config\022\021\n\ttimestamp\030\003 \001(\003" +
      "\022\037\n\027disable_balanced_update\030\004 \001(\010:\004\250\246\037\001:" +
      "\004\250\246\037\001\"\300\004\n\006Upsert\032o\n\007Request\0223\n\006vector\030\001 " +
      "\001(\0132\031.payload.v1.Object.VectorB\010\372B\005\222\001\002\010\002" +
      "\022)\n\006config\030\002 \001(\0132\031.payload.v1.Upsert.Con" +
      "fig:\004\250\246\037\001\032B\n\014MultiRequest\022,\n\010requests\030\001 " +
      "\003(\0132\032.payload.v1.Upsert.Request:\004\250\246\037\001\032\230\001" +
      "\n\rObjectRequest\022\'\n\006object\030\001 \001(\0132\027.payloa" +
      "d.v1.Object.Blob\022)\n\006config\030\002 \001(\0132\031.paylo" +
      "ad.v1.Upsert.Config\022-\n\nvectorizer\030\003 \001(\0132" +
      "\031.payload.v1.Filter.Target:\004\250\246\037\001\032N\n\022Mult" +
      "iObjectRequest\0222\n\010requests\030\001 \003(\0132 .paylo" +
      "ad.v1.Upsert.ObjectRequest:\004\250\246\037\001\032\217\001\n\006Con" +
      "fig\022\037\n\027skip_strict_exist_check\030\001 \001(\010\022*\n\007" +
      "filters\030\002 \001(\0132\031.payload.v1.Filter.Config" +
      "\022\021\n\ttimestamp\030\003 \001(\003\022\037\n\027disable_balanced_" +
      "update\030\004 \001(\010:\004\250\246\037\001:\004\250\246\037\001\"\365\001\n\006Remove\032]\n\007R" +
      "equest\022!\n\002id\030\001 \001(\0132\025.payload.v1.Object.I" +
      "D\022)\n\006config\030\002 \001(\0132\031.payload.v1.Remove.Co" +
      "nfig:\004\250\246\037\001\032B\n\014MultiRequest\022,\n\010requests\030\001" +
      " \003(\0132\032.payload.v1.Remove.Request:\004\250\246\037\001\032B" +
      "\n\006Config\022\037\n\027skip_strict_exist_check\030\001 \001(" +
      "\010\022\021\n\ttimestamp\030\003 \001(\003:\004\250\246\037\001:\004\250\246\037\001\"\212\010\n\006Obj" +
      "ect\032n\n\rVectorRequest\022+\n\002id\030\001 \001(\0132\025.paylo" +
      "ad.v1.Object.IDB\010\372B\005\222\001\002\010\002\022*\n\007filters\030\002 \001" +
      "(\0132\031.payload.v1.Filter.Config:\004\250\246\037\001\032.\n\010D" +
      "istance\022\n\n\002id\030\001 \001(\t\022\020\n\010distance\030\002 \001(\002:\004\250" +
      "\246\037\001\032r\n\016StreamDistance\022/\n\010distance\030\001 \001(\0132" +
      "\033.payload.v1.Object.DistanceH\000\022$\n\006status" +
      "\030\002 \001(\0132\022.google.rpc.StatusH\000B\t\n\007payload\032" +
      "\037\n\002ID\022\023\n\002id\030\001 \001(\tB\007\372B\004r\002\020\001:\004\250\246\037\001\032\030\n\003IDs\022" +
      "\013\n\003ids\030\001 \003(\t:\004\250\246\037\001\032=\n\006Vector\022\023\n\002id\030\001 \001(\t" +
      "B\007\372B\004r\002\020\001\022\030\n\006vector\030\002 \003(\002B\010\372B\005\222\001\002\010\002:\004\250\246\037" +
      "\001\032;\n\007Vectors\022*\n\007vectors\030\001 \003(\0132\031.payload." +
      "v1.Object.Vector:\004\250\246\037\001\032l\n\014StreamVector\022+" +
      "\n\006vector\030\001 \001(\0132\031.payload.v1.Object.Vecto" +
      "rH\000\022$\n\006status\030\002 \001(\0132\022.google.rpc.StatusH" +
      "\000B\t\n\007payload\0324\n\rReshapeVector\022\016\n\006object\030" +
      "\001 \001(\014\022\r\n\005shape\030\002 \003(\005:\004\250\246\037\001\0321\n\004Blob\022\023\n\002id" +
      "\030\001 \001(\tB\007\372B\004r\002\020\001\022\016\n\006object\030\002 \001(\014:\004\250\246\037\001\032f\n" +
      "\nStreamBlob\022\'\n\004blob\030\001 \001(\0132\027.payload.v1.O" +
      "bject.BlobH\000\022$\n\006status\030\002 \001(\0132\022.google.rp" +
      "c.StatusH\000B\t\n\007payload\0329\n\010Location\022\014\n\004nam" +
      "e\030\001 \001(\t\022\014\n\004uuid\030\002 \001(\t\022\013\n\003ips\030\003 \003(\t:\004\250\246\037\001" +
      "\032r\n\016StreamLocation\022/\n\010location\030\001 \001(\0132\033.p" +
      "ayload.v1.Object.LocationH\000\022$\n\006status\030\002 " +
      "\001(\0132\022.google.rpc.StatusH\000B\t\n\007payload\032A\n\t" +
      "Locations\022.\n\tlocations\030\001 \003(\0132\033.payload.v" +
      "1.Object.Location:\004\250\246\037\001:\004\250\246\037\001\"G\n\007Control" +
      "\0326\n\022CreateIndexRequest\022\032\n\tpool_size\030\001 \001(" +
      "\rB\007\372B\004*\002(\000:\004\250\246\037\001:\004\250\246\037\001\"[\n\nDiscoverer\032G\n\007" +
      "Request\022\025\n\004name\030\001 \001(\tB\007\372B\004r\002\020\001\022\021\n\tnamesp" +
      "ace\030\002 \001(\t\022\014\n\004node\030\003 \001(\t:\004\250\246\037\001:\004\250\246\037\001\"\312\006\n\004" +
      "Info\032\251\001\n\005Index\032T\n\005Count\022\016\n\006stored\030\001 \001(\r\022" +
      "\023\n\013uncommitted\030\002 \001(\r\022\020\n\010indexing\030\003 \001(\010\022\016" +
      "\n\006saving\030\004 \001(\010:\004\250\246\037\001\032D\n\004UUID\032\031\n\tCommitte" +
      "d\022\014\n\004uuid\030\001 \001(\t\032\033\n\013Uncommitted\022\014\n\004uuid\030\001" +
      " \001(\t:\004\250\246\037\001:\004\250\246\037\001\032\304\001\n\003Pod\022\020\n\010app_name\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tnamespace\030\003 \001(\t\022\023\n\002i" +
      "p\030\004 \001(\tB\007\372B\004r\002x\001\022!\n\003cpu\030\005 \001(\0132\024.payload." +
      "v1.Info.CPU\022\'\n\006memory\030\006 \001(\0132\027.payload.v1" +
      ".Info.Memory\022#\n\004node\030\007 \001(\0132\025.payload.v1." +
      "Info.Node:\004\250\246\037\001\032\271\001\n\004Node\022\014\n\004name\030\001 \001(\t\022\025" +
      "\n\rinternal_addr\030\002 \001(\t\022\025\n\rexternal_addr\030\003" +
      " \001(\t\022!\n\003cpu\030\004 \001(\0132\024.payload.v1.Info.CPU\022" +
      "\'\n\006memory\030\005 \001(\0132\027.payload.v1.Info.Memory" +
      "\022#\n\004Pods\030\006 \001(\0132\025.payload.v1.Info.Pods:\004\250" +
      "\246\037\001\032:\n\003CPU\022\r\n\005limit\030\001 \001(\001\022\017\n\007request\030\002 \001" +
      "(\001\022\r\n\005usage\030\003 \001(\001:\004\250\246\037\001\032=\n\006Memory\022\r\n\005lim" +
      "it\030\001 \001(\001\022\017\n\007request\030\002 \001(\001\022\r\n\005usage\030\003 \001(\001" +
      ":\004\250\246\037\001\032:\n\004Pods\022,\n\004pods\030\001 \003(\0132\024.payload.v" +
      "1.Info.PodB\010\372B\005\222\001\002\010\001:\004\250\246\037\001\032=\n\005Nodes\022.\n\005n" +
      "odes\030\001 \003(\0132\025.payload.v1.Info.NodeB\010\372B\005\222\001" +
      "\002\010\001:\004\250\246\037\001\032\027\n\003IPs\022\n\n\002ip\030\001 \003(\t:\004\250\246\037\001:\004\250\246\037\001" +
      "\"\007\n\005EmptyBZ\n\035org.vdaas.vald.api.v1.paylo" +
      "adB\013ValdPayloadP\001Z*github.com/vdaas/vald" +
      "/apis/grpc/v1/payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
          com.google.protobuf.VTProto.getDescriptor(),
        });
    internal_static_payload_v1_Search_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payload_v1_Search_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Search_Request_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Search_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_Request_descriptor,
        new java.lang.String[] { "Vector", "Config", });
    internal_static_payload_v1_Search_MultiRequest_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Search_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_MultiRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Search_IDRequest_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Search_IDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_IDRequest_descriptor,
        new java.lang.String[] { "Id", "Config", });
    internal_static_payload_v1_Search_MultiIDRequest_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Search_MultiIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_MultiIDRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Search_ObjectRequest_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Search_ObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_ObjectRequest_descriptor,
        new java.lang.String[] { "Object", "Config", "Vectorizer", });
    internal_static_payload_v1_Search_MultiObjectRequest_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(5);
    internal_static_payload_v1_Search_MultiObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_MultiObjectRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Search_Config_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(6);
    internal_static_payload_v1_Search_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_Config_descriptor,
        new java.lang.String[] { "RequestId", "Num", "Radius", "Epsilon", "Timeout", "IngressFilters", "EgressFilters", "MinNum", "AggregationAlgorithm", });
    internal_static_payload_v1_Search_Response_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(7);
    internal_static_payload_v1_Search_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_Response_descriptor,
        new java.lang.String[] { "RequestId", "Results", });
    internal_static_payload_v1_Search_Responses_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(8);
    internal_static_payload_v1_Search_Responses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_Responses_descriptor,
        new java.lang.String[] { "Responses", });
    internal_static_payload_v1_Search_StreamResponse_descriptor =
      internal_static_payload_v1_Search_descriptor.getNestedTypes().get(9);
    internal_static_payload_v1_Search_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Search_StreamResponse_descriptor,
        new java.lang.String[] { "Response", "Status", "Payload", });
    internal_static_payload_v1_Filter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payload_v1_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Filter_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Filter_Target_descriptor =
      internal_static_payload_v1_Filter_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Filter_Target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Filter_Target_descriptor,
        new java.lang.String[] { "Host", "Port", });
    internal_static_payload_v1_Filter_Config_descriptor =
      internal_static_payload_v1_Filter_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Filter_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Filter_Config_descriptor,
        new java.lang.String[] { "Targets", });
    internal_static_payload_v1_Insert_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_payload_v1_Insert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Insert_Request_descriptor =
      internal_static_payload_v1_Insert_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Insert_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_Request_descriptor,
        new java.lang.String[] { "Vector", "Config", });
    internal_static_payload_v1_Insert_MultiRequest_descriptor =
      internal_static_payload_v1_Insert_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Insert_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_MultiRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Insert_ObjectRequest_descriptor =
      internal_static_payload_v1_Insert_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Insert_ObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_ObjectRequest_descriptor,
        new java.lang.String[] { "Object", "Config", "Vectorizer", });
    internal_static_payload_v1_Insert_MultiObjectRequest_descriptor =
      internal_static_payload_v1_Insert_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Insert_MultiObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_MultiObjectRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Insert_Config_descriptor =
      internal_static_payload_v1_Insert_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Insert_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Insert_Config_descriptor,
        new java.lang.String[] { "SkipStrictExistCheck", "Filters", "Timestamp", });
    internal_static_payload_v1_Update_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_payload_v1_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Update_Request_descriptor =
      internal_static_payload_v1_Update_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Update_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_Request_descriptor,
        new java.lang.String[] { "Vector", "Config", });
    internal_static_payload_v1_Update_MultiRequest_descriptor =
      internal_static_payload_v1_Update_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Update_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_MultiRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Update_ObjectRequest_descriptor =
      internal_static_payload_v1_Update_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Update_ObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_ObjectRequest_descriptor,
        new java.lang.String[] { "Object", "Config", "Vectorizer", });
    internal_static_payload_v1_Update_MultiObjectRequest_descriptor =
      internal_static_payload_v1_Update_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Update_MultiObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_MultiObjectRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Update_Config_descriptor =
      internal_static_payload_v1_Update_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Update_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Update_Config_descriptor,
        new java.lang.String[] { "SkipStrictExistCheck", "Filters", "Timestamp", "DisableBalancedUpdate", });
    internal_static_payload_v1_Upsert_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_payload_v1_Upsert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Upsert_Request_descriptor =
      internal_static_payload_v1_Upsert_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Upsert_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_Request_descriptor,
        new java.lang.String[] { "Vector", "Config", });
    internal_static_payload_v1_Upsert_MultiRequest_descriptor =
      internal_static_payload_v1_Upsert_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Upsert_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_MultiRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Upsert_ObjectRequest_descriptor =
      internal_static_payload_v1_Upsert_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Upsert_ObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_ObjectRequest_descriptor,
        new java.lang.String[] { "Object", "Config", "Vectorizer", });
    internal_static_payload_v1_Upsert_MultiObjectRequest_descriptor =
      internal_static_payload_v1_Upsert_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Upsert_MultiObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_MultiObjectRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Upsert_Config_descriptor =
      internal_static_payload_v1_Upsert_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Upsert_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Upsert_Config_descriptor,
        new java.lang.String[] { "SkipStrictExistCheck", "Filters", "Timestamp", "DisableBalancedUpdate", });
    internal_static_payload_v1_Remove_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_payload_v1_Remove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Remove_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Remove_Request_descriptor =
      internal_static_payload_v1_Remove_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Remove_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Remove_Request_descriptor,
        new java.lang.String[] { "Id", "Config", });
    internal_static_payload_v1_Remove_MultiRequest_descriptor =
      internal_static_payload_v1_Remove_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Remove_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Remove_MultiRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_payload_v1_Remove_Config_descriptor =
      internal_static_payload_v1_Remove_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Remove_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Remove_Config_descriptor,
        new java.lang.String[] { "SkipStrictExistCheck", "Timestamp", });
    internal_static_payload_v1_Object_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_payload_v1_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Object_VectorRequest_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Object_VectorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_VectorRequest_descriptor,
        new java.lang.String[] { "Id", "Filters", });
    internal_static_payload_v1_Object_Distance_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Object_Distance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Distance_descriptor,
        new java.lang.String[] { "Id", "Distance", });
    internal_static_payload_v1_Object_StreamDistance_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Object_StreamDistance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_StreamDistance_descriptor,
        new java.lang.String[] { "Distance", "Status", "Payload", });
    internal_static_payload_v1_Object_ID_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Object_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_ID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_payload_v1_Object_IDs_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Object_IDs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_IDs_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_payload_v1_Object_Vector_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(5);
    internal_static_payload_v1_Object_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Vector_descriptor,
        new java.lang.String[] { "Id", "Vector", });
    internal_static_payload_v1_Object_Vectors_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(6);
    internal_static_payload_v1_Object_Vectors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Vectors_descriptor,
        new java.lang.String[] { "Vectors", });
    internal_static_payload_v1_Object_StreamVector_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(7);
    internal_static_payload_v1_Object_StreamVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_StreamVector_descriptor,
        new java.lang.String[] { "Vector", "Status", "Payload", });
    internal_static_payload_v1_Object_ReshapeVector_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(8);
    internal_static_payload_v1_Object_ReshapeVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_ReshapeVector_descriptor,
        new java.lang.String[] { "Object", "Shape", });
    internal_static_payload_v1_Object_Blob_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(9);
    internal_static_payload_v1_Object_Blob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Blob_descriptor,
        new java.lang.String[] { "Id", "Object", });
    internal_static_payload_v1_Object_StreamBlob_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(10);
    internal_static_payload_v1_Object_StreamBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_StreamBlob_descriptor,
        new java.lang.String[] { "Blob", "Status", "Payload", });
    internal_static_payload_v1_Object_Location_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(11);
    internal_static_payload_v1_Object_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Location_descriptor,
        new java.lang.String[] { "Name", "Uuid", "Ips", });
    internal_static_payload_v1_Object_StreamLocation_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(12);
    internal_static_payload_v1_Object_StreamLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_StreamLocation_descriptor,
        new java.lang.String[] { "Location", "Status", "Payload", });
    internal_static_payload_v1_Object_Locations_descriptor =
      internal_static_payload_v1_Object_descriptor.getNestedTypes().get(13);
    internal_static_payload_v1_Object_Locations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Object_Locations_descriptor,
        new java.lang.String[] { "Locations", });
    internal_static_payload_v1_Control_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_payload_v1_Control_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Control_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Control_CreateIndexRequest_descriptor =
      internal_static_payload_v1_Control_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Control_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Control_CreateIndexRequest_descriptor,
        new java.lang.String[] { "PoolSize", });
    internal_static_payload_v1_Discoverer_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_payload_v1_Discoverer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Discoverer_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Discoverer_Request_descriptor =
      internal_static_payload_v1_Discoverer_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Discoverer_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Discoverer_Request_descriptor,
        new java.lang.String[] { "Name", "Namespace", "Node", });
    internal_static_payload_v1_Info_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_payload_v1_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Info_Index_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Info_Index_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Index_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Info_Index_Count_descriptor =
      internal_static_payload_v1_Info_Index_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Info_Index_Count_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Index_Count_descriptor,
        new java.lang.String[] { "Stored", "Uncommitted", "Indexing", "Saving", });
    internal_static_payload_v1_Info_Index_UUID_descriptor =
      internal_static_payload_v1_Info_Index_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Info_Index_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Index_UUID_descriptor,
        new java.lang.String[] { });
    internal_static_payload_v1_Info_Index_UUID_Committed_descriptor =
      internal_static_payload_v1_Info_Index_UUID_descriptor.getNestedTypes().get(0);
    internal_static_payload_v1_Info_Index_UUID_Committed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Index_UUID_Committed_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_v1_Info_Index_UUID_Uncommitted_descriptor =
      internal_static_payload_v1_Info_Index_UUID_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Info_Index_UUID_Uncommitted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Index_UUID_Uncommitted_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_payload_v1_Info_Pod_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(1);
    internal_static_payload_v1_Info_Pod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Pod_descriptor,
        new java.lang.String[] { "AppName", "Name", "Namespace", "Ip", "Cpu", "Memory", "Node", });
    internal_static_payload_v1_Info_Node_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(2);
    internal_static_payload_v1_Info_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Node_descriptor,
        new java.lang.String[] { "Name", "InternalAddr", "ExternalAddr", "Cpu", "Memory", "Pods", });
    internal_static_payload_v1_Info_CPU_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(3);
    internal_static_payload_v1_Info_CPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_CPU_descriptor,
        new java.lang.String[] { "Limit", "Request", "Usage", });
    internal_static_payload_v1_Info_Memory_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(4);
    internal_static_payload_v1_Info_Memory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Memory_descriptor,
        new java.lang.String[] { "Limit", "Request", "Usage", });
    internal_static_payload_v1_Info_Pods_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(5);
    internal_static_payload_v1_Info_Pods_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Pods_descriptor,
        new java.lang.String[] { "Pods", });
    internal_static_payload_v1_Info_Nodes_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(6);
    internal_static_payload_v1_Info_Nodes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_Nodes_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_payload_v1_Info_IPs_descriptor =
      internal_static_payload_v1_Info_descriptor.getNestedTypes().get(7);
    internal_static_payload_v1_Info_IPs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Info_IPs_descriptor,
        new java.lang.String[] { "Ip", });
    internal_static_payload_v1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_payload_v1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payload_v1_Empty_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    registry.add(com.google.protobuf.VTProto.mempool);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.protobuf.VTProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
