// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vald/apis/proto/v1/vald/filter.proto

package org.vdaas.vald.api.v1.vald;

public final class ValdFilter {
  private ValdFilter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$vald/apis/proto/v1/vald/filter.proto\022\007" +
      "vald.v1\032#apis/proto/v1/payload/payload.p" +
      "roto\032-github.com/gogo/protobuf/gogoproto" +
      "/gogo.proto\0327github.com/gogo/googleapis/" +
      "google/api/annotations.proto2\350\007\n\006Filter\022" +
      "h\n\014SearchObject\022 .payload.v1.Search.Obje" +
      "ctRequest\032\033.payload.v1.Search.Response\"\031" +
      "\202\323\344\223\002\023\"\016/search/object:\001*\022_\n\022StreamSearc" +
      "hObject\022 .payload.v1.Search.ObjectReques" +
      "t\032!.payload.v1.Search.StreamResponse\"\000(\001" +
      "0\001\022_\n\014InsertObject\022\027.payload.v1.Object.B" +
      "lob\032\033.payload.v1.Object.Location\"\031\202\323\344\223\002\023" +
      "\"\016/insert/object:\001*\022V\n\022StreamInsertObjec" +
      "t\022\027.payload.v1.Object.Blob\032!.payload.v1." +
      "Object.StreamLocation\"\000(\0010\001\022L\n\021MultiInse" +
      "rtObject\022\027.payload.v1.Object.Blob\032\034.payl" +
      "oad.v1.Object.Locations\"\000\022_\n\014UpdateObjec" +
      "t\022\027.payload.v1.Object.Blob\032\033.payload.v1." +
      "Object.Location\"\031\202\323\344\223\002\023\"\016/update/object:" +
      "\001*\022V\n\022StreamUpdateObject\022\027.payload.v1.Ob" +
      "ject.Blob\032!.payload.v1.Object.StreamLoca" +
      "tion\"\000(\0010\001\022L\n\021MultiUpdateObject\022\027.payloa" +
      "d.v1.Object.Blob\032\034.payload.v1.Object.Loc" +
      "ations\"\000\022_\n\014UpsertObject\022\027.payload.v1.Ob" +
      "ject.Blob\032\033.payload.v1.Object.Location\"\031" +
      "\202\323\344\223\002\023\"\016/upsert/object:\001*\022V\n\022StreamUpser" +
      "tObject\022\027.payload.v1.Object.Blob\032!.paylo" +
      "ad.v1.Object.StreamLocation\"\000(\0010\001\022L\n\021Mul" +
      "tiUpsertObject\022\027.payload.v1.Object.Blob\032" +
      "\034.payload.v1.Object.Locations\"\000Bg\n\032org.v" +
      "daas.vald.api.v1.valdB\nValdFilterP\001Z\'git" +
      "hub.com/vdaas/vald/apis/grpc/v1/vald\310\342\036\001" +
      "\320\342\036\001\340\342\036\001\300\343\036\001\310\343\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoRegistration);
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.messagenameAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
