on:
  workflow_call:
    inputs:
      notify_slack_if_failed:
        type: boolean
        description: "Notify Slack if e2e failed"
        required: false
        default: true
  
jobs:
  java_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print java version
        id: java_version
        run: |
          latest_java_version=`make vald/java/version/latest`
          stable_java_version=`make vald/java/version/stable`
          echo "LATEST_JAVA_VERSION=${latest_java_version}" >> $GITHUB_OUTPUT
          echo "STABLE_JAVA_VERSION=${stable_java_version}" >> $GITHUB_OUTPUT
    outputs:
      LATEST_JAVA_VERSION: ${{ steps.java_version.outputs.LATEST_JAVA_VERSION }}
      STABLE_JAVA_VERSION: ${{ steps.java_version.outputs.STABLE_JAVA_VERSION }}

  e2e_latest:
    name: E2E for latest version
    needs: java_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/e2e
        with:
          notify_slack_if_failed: false
          java_version: ${{ needs.java_version.outputs.LATEST_JAVA_VERSION }}

  e2e_stable:
    name: E2E for stable version
    needs: java_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/e2e
        with:
          notify_slack_if_failed: false
          java_version: ${{ needs.java_version.outputs.STABLE_JAVA_VERSION }}

  notify_slack_when_e2e_failed:
    name: Notify Slack when E2E failed
    runs-on: ubuntu-latest
    needs:
      - e2e_latest
      - e2e_stable
    if: ${{ always() && (needs.e2e_latest.result == 'failure' || needs.e2e_stable.result == 'failure') && inputs.notify_slack_if_failed }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/notify-slack
        with:
          author_name: E2E failed on PR
          slack_notify_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: failure