on:
  workflow_call:

jobs:
  merge_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh pr merge -s --auto -d "${{github.event.pull_request.html_url}}"