on:
  pull_request:

jobs:
  e2e:
    uses: ./.github/workflows/_e2e.yaml
  merge_pr_when_e2e_success:
    name: Merge PR when E2E success
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - e2e
    if: ${{ always() && needs.e2e.result == 'success' && contains('["dependabot","github-actions"]', github.event.pull_request.user.login) }}
    steps:
      - name: Merge PR
        run: |
          gh pr merge --merge --auto "${{github.event.pull_request.html_url}}"
  notify_slack_when_e2e_failed:
    name: Notify Slack when E2E failed
    runs-on: ubuntu-latest
    needs:
      - e2e
    if: ${{ always() && needs.e2e.result == 'failure' && contains('["dependabot","github-actions"]', github.event.pull_request.user.login) }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Java client E2E FAILED!*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 
        if: success()