on:
  pull_request:

jobs:
  rebase:
    name: Rebase and merge
    if: ${{ github.event.pull_request.user.login == 'github-actions' || github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Rebase
        uses: cirrus-actions/rebase@1.8

  e2e:
    runs-on: ubuntu-latest
    needs: rebase
    steps:
      - name: Print java version
        id: java_version
        run: |
          latest_java_version = `make vald/java/version/latest`
          stable_java_version = `make vald/java/version/stable`
          echo "LATEST_JAVA_VERSION=${latest_java_version}" >> $GITHUB_OUTPUT
          echo "STABLE_JAVA_VERSION=${stable_java_version}" >> $GITHUB_OUTPUT
      - name: e2e_latest
        uses: ./.github/workflows/_e2e.yml
        with:
          notify_slack_if_failed: false
          java_version: ${{ steps.java_version.outputs.LATEST_JAVA_VERSION }}
      - name: e2e_stable
        uses: ./.github/workflows/_e2e.yml
        with:
          notify_slack_if_failed: false
          java_version: ${{ steps.java_version.outputs.STABLE_JAVA_VERSION }}

  merge_pr:
    name: Merge PR
    needs:
      - e2e
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh pr merge -s --auto -d "${{github.event.pull_request.html_url}}"