on:
  pull_request:

jobs:
  rebase:
    name: Rebase and merge
    if: ${{ github.event.pull_request.user.login == 'github-actions' || github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Rebase
        uses: cirrus-actions/rebase@1.8

  e2e:
    name: e2e
    needs:
      - rebase
    uses: ./.github/workflows/_e2e_multi.yml
    with:
      notify_slack_if_failed: true

  merge_pr:
    name: Merge PR
    needs:
      - e2e
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh pr merge -s --auto -d "${{github.event.pull_request.html_url}}"