on:
  pull_request:

jobs:
  
  e2e:
    name: e2e
    if: ${{ github.event.pull_request.user.login != 'github-actions' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    uses: ./.github/workflows/_e2e_multi.yml
    with:
      notify_slack_if_failed: false