on:
  pull_request:

jobs:
  e2e:
    uses: "./.github/workflows/_e2e.yaml"
    if: ${{ !contains('["dependabot","github-actions"]', github.event.pull_request.user.login) }}
    with:
      notify_slack_if_failed: false