on:
  pull_request:

jobs:
  e2e:
    uses: "./.github/workflows/_e2e.yml"
    if: ${{ github.event.pull_request.user.login != 'github-actions' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    with:
      notify_slack_if_failed: false