name: release
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build protobuf
        run: |
          export GOPATH=$HOME/go
          export PATH=$HOME/grpc-java:$PATH
          make all
      - uses: rinx/setup-k3d@v0.0.4
        with:
          version: latest
          name: vald
          agents: 1
      - name: check k3d
        run: |
          kubectl cluster-info
      - uses: azure/setup-helm@v3
      - name: Helm version
        run: |
          helm version
      - name: deploy Vald
        run: |
          helm repo add vald https://vald.vdaas.org/charts
          helm install \
            --values ${VALUES} \
            --set defaults.image.tag=nightly \
            --set agent.ngt.dimension=300 \
            --set agent.ngt.auto_index_length=2 \
            --set agent.minReplicas=1 \
            --set gateway.lb.enabled=false \
            --set discoverer.enabled=false \
            --set manager.index.enabled=false \
            --generate-name vald/vald
          sleep 3
          kubectl wait --for=condition=ready pod -l app=vald-agent-ngt --timeout=3m
          kubectl get pods
        env:
          VALUES: https://raw.githubusercontent.com/vdaas/vald/main/.github/helm/values/values-lb.yaml
      - name: Download data
        run: |
          curl -OL https://raw.githubusercontent.com/rinx/word2vecjson/master/data/wordvecs1000.json
      - name: run tests
        run: |
          kubectl port-forward statefulset/vald-agent-ngt 8081:8081 &
          pid=$!

          ./gradlew test

          kill $pid
  release:
    if: startsWith( github.ref, 'refs/tags/')
    needs:
      - e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        if: startsWith( github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  publish:
    if: startsWith( github.ref, 'refs/tags/')
    needs:
      - e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: prepare for publish
        run: |
          ./gradlew clean
          echo "${PGP_PRIVATE_KEY}" > private_key.txt
          gpg --import --batch private_key.txt
          rm -f private_key.txt
          gpg --pinentry-mode loopback --passphrase "${GPG_PASSPHRASE}" --export-secret-keys -o ~/.gnupg/secring.gpg
          cat << EOF > ~/.gradle/gradle.properties
          org.gradle.daemon=true
          signing.keyId=${GPG_KEYID}
          signing.password=${GPG_PASSPHRASE}
          signing.secretKeyRingFile=${HOME}/.gnupg/secring.gpg
          sonatypeUsername=${SONATYPE_USERNAME}
          sonatypePassword=${SONATYPE_PASSWORD}
          nexusUsername=${SONATYPE_USERNAME}
          nexusPassword=${SONATYPE_PASSWORD}
          EOF
        env:
          GPG_KEYID: ${{ secrets.GPG_KEYID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: publish
        run: |
          ./gradlew clean
          ./gradlew build -x test --stacktrace
          ./gradlew publish -Prelease --stacktrace
          sleep 120
          ./gradlew closeAndReleaseRepository --stacktrace
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  merge_pr_when_e2e_success:
    name: Merge PR when E2E success
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - e2e
    if: ${{ always() && github.event_name == 'pull_request' && needs.e2e.result == 'success' && contains('["dependabot","github-actions"]', github.event.pull_request.user.login) }}
    steps:
      - name: Merge PR
        run: |
          gh pr merge --merge --auto "${{github.event.pull_request.html_url}}"
  notify_slack_when_e2e_failed:
    name: Notify Slack when E2E failed
    runs-on: ubuntu-latest
    needs:
      - e2e
    if: ${{ always() && github.event_name == 'pull_request' && needs.e2e.result == 'failure' && contains('["dependabot","github-actions"]', github.event.pull_request.user.login) }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Java client E2E FAILED!*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 
        if: success()
  notify_slack_when_release_succeed:
    name: Notify Slack when release succeed
    runs-on: ubuntu-latest
    needs:
      - publish
      - release
    if: ${{ always() && github.event_name != 'pull_request' && needs.publish.result == 'success' && needs.release.result == 'success' }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Java client release successed!\"}}]}' 
        if: success()
  notify_slack_when_release_failed:
    name: Notify Slack when release failed
    runs-on: ubuntu-latest
    needs:
      - publish
      - release
    if: ${{ always() && github.event_name != 'pull_request' && contains(join(needs.*.result, ','), 'failure') }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Java client release FAILED!*\"}}]}' 
        if: success()